//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Birth day.
        /// </summary>
        internal static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates.
        /// </summary>
        internal static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - enter action.
        /// </summary>
        internal static string CaseA {
            get {
                return ResourceManager.GetString("CaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - enter ingestion.
        /// </summary>
        internal static string CaseE {
            get {
                return ResourceManager.GetString("CaseE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  gender :.
        /// </summary>
        internal static string EnterGender {
            get {
                return ResourceManager.GetString("EnterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats.
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of .
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of birth day .
        /// </summary>
        internal static string FormatBd {
            get {
                return ResourceManager.GetString("FormatBd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proteins.
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter type of Action.
        /// </summary>
        internal static string TypeAction {
            get {
                return ResourceManager.GetString("TypeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight of food.
        /// </summary>
        internal static string weightFood {
            get {
                return ResourceManager.GetString("weightFood", resourceCulture);
            }
        }
    }
}
